name: Build and Release Python Package

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build tools
      run: pip install build

    - name: Get version from setup.py
      id: get_version
      run: |
        VERSION=$(python setup.py --version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build package to dist/<version>/
      run: |
        mkdir -p dist/${{ steps.get_version.outputs.version }}
        python -m build --outdir dist/${{ steps.get_version.outputs.version }}

    - name: Commit build artifacts (optional)
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add dist/${{ steps.get_version.outputs.version }}
        git commit -m "Add build artifacts for version ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
        git push

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: v${{ steps.get_version.outputs.version }}
        files: dist/${{ steps.get_version.outputs.version }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
