name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build tools
      run: pip install build twine

    - name: Get package version
      id: get_version
      run: |
        VERSION=$(python setup.py --version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build package into versioned dist folder
      run: |
        mkdir -p dist/${{ steps.get_version.outputs.version }}
        python -m build --outdir dist/${{ steps.get_version.outputs.version }}

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/${{ steps.get_version.outputs.version }}/*
